# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "aea94c61872475e46c88d674875590b5"
name = "Courtyard Checkout Rules"
application_url = "https://courtyard-checkout-rules.vercel.app"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_delivery_customizations,read_metaobject_definitions,write_metaobject_definitions,read_metaobjects,write_metaobjects,read_products,read_metafields,write_metafields,read_validations,write_validations"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://courtyard-checkout-rules.vercel.app/auth/callback",
  "https://courtyard-checkout-rules.vercel.app/auth/shopify/callback",
  "https://courtyard-checkout-rules.vercel.app/api/auth/callback"
]
